## Python Arrays

Note: Python does not have built-in support for Arrays, but Python Lists can be used instead.

Note: This page shows you how to use LISTS as ARRAYS, however, to work with arrays in Python you will have to import a library, like the NumPy library.

In [1]:
#   Create an array containing car names:

cars = ["Ford", "Volvo", "BMW"]

print(cars)

for x in cars:
    print(x)

['Ford', 'Volvo', 'BMW']
Ford
Volvo
BMW


In [2]:
car1 = "Ford"
car2 = "Volvo"
car3 = "BMW"

print(car1)
print(car2)
print(car3)

Ford
Volvo
BMW


In [4]:
car1, car2, car3 = ["Ford", "Volvo", "BMW"]

print(car1)
print(car2)
print(car3)

Ford
Volvo
BMW


In [7]:
# length of Array
cars = ["Ford", "Volvo", "BMW"]
print(len(cars))

3


In [8]:
# Looping Array Elements
cars = ["Ford", "Volvo", "BMW"]
for x in cars:
    print(x)

Ford
Volvo
BMW


In [9]:
# Adding Array Elements
cars = ["Ford", "Volvo", "BMW"]
cars.append("Honda")
print(cars)

['Ford', 'Volvo', 'BMW', 'Honda']


In [ ]:
# Removing Array Elements

cars = ["Ford", "Volvo", "BMW", "Honda"]
cars.pop()
print(cars)
cars = ["Ford", "Volvo", "BMW"]
cars.pop(1)
cars.remove("Volvo")
print(cars)

## Array Methods

Method	    Description
append()	Adds an element at the end of the list
clear()	    Removes all the elements from the list
copy()	    Returns a copy of the list
count()	    Returns the number of elements with the specified value
extend()	Add the elements of a list (or any iterable), to the end of the current list
index()	    Returns the index of the first element with the specified value
insert()	Adds an element at the specified position
pop()	    Removes the element at the specified position
remove()	Removes the first item with the specified value
reverse()	Reverses the order of the list
sort()	    Sorts the list

Understanding of Numpy

In [3]:
import numpy as np
import random 

rolls = np.random.randint(1, 7, size=10)
rolls

array([2, 2, 5, 5, 5, 4, 4, 1, 5, 3], dtype=int32)

In [4]:
type(rolls)

numpy.ndarray

In [ ]:
# what can we do with rolls?
# We can perform various operations on the array, such as statistical analysis, reshaping, and mathematical operations.
print(dir(rolls))

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_namespace__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__buffer__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__'

In [6]:
rolls.mean()

np.float64(3.6)

In [10]:
a = rolls.tolist()
print(a)
print(type(a), type(rolls))

[2, 2, 5, 5, 5, 4, 4, 1, 5, 3]
<class 'list'> <class 'numpy.ndarray'>


In [13]:
help(rolls.ravel)

Help on built-in function ravel:

ravel(order='C') method of numpy.ndarray instance
    a.ravel(order='C')

    Return a flattened array.

    Refer to `numpy.ravel` for full documentation.

    See Also
    --------
    numpy.ravel : equivalent function
    ndarray.flat : a flat iterator on the array.



In [15]:
[3,4,5,6,7] + [10]

[3, 4, 5, 6, 7, 10]

In [18]:
rolls = np.random.randint(1, 7, size=10)
rolls

array([1, 2, 2, 5, 5, 5, 3, 1, 6, 6], dtype=int32)

In [21]:
rolls <=5

array([ True,  True,  True,  True,  True,  True,  True,  True, False,
       False])

In [20]:
rolls + 10 # adding 10 to each element in the array

array([11, 12, 12, 15, 15, 15, 13, 11, 16, 16], dtype=int32)

Tensor Operation

In [ ]:
# ! pip install tensorflow

In [22]:
import tensorflow as tf
# Create two constants, each with value 1
a = tf.constant(1)
b = tf.constant(1)
# Add them together to get...
a + b

<tf.Tensor: shape=(), dtype=int32, numpy=2>

Understanding how Python's operators work when applied to ints, strings, and lists is no guarantee that you'll be able to immediately understand what they do when applied to a tensorflow Tensor, or a numpy ndarray, or a pandas DataFrame.